SET search_path = public;

CREATE TABLE customers (
  customer_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name   VARCHAR(255) NOT NULL,
  last_name    VARCHAR(255) NOT NULL,
  phone        VARCHAR(50),
  email        VARCHAR(255) UNIQUE,
  street       VARCHAR(255),
  city         VARCHAR(100),
  state        VARCHAR(100),
  zip_code     VARCHAR(20)
);

CREATE TABLE stores (
  store_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_name VARCHAR(255) NOT NULL,
  phone      VARCHAR(50),
  email      VARCHAR(255) UNIQUE,
  street     VARCHAR(255),
  city       VARCHAR(100),
  state      VARCHAR(100),
  zip_code   VARCHAR(20)
);

CREATE TABLE staffs (
  staff_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name  VARCHAR(255) NOT NULL,
  email      VARCHAR(255) UNIQUE,
  phone      VARCHAR(50),
  active     BOOLEAN NOT NULL DEFAULT TRUE,
  store_id   INTEGER NOT NULL REFERENCES stores(store_id) ON DELETE RESTRICT,
  manager_id INTEGER REFERENCES staffs(staff_id) ON DELETE SET NULL
);

CREATE TABLE categories (
  category_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR(255) NOT NULL
);

CREATE TABLE brands (
  brand_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_name VARCHAR(255) NOT NULL
);

CREATE TABLE products (
  product_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_name VARCHAR(255) NOT NULL,
  brand_id     INTEGER NOT NULL REFERENCES brands(brand_id) ON DELETE RESTRICT,
  category_id  INTEGER NOT NULL REFERENCES categories(category_id) ON DELETE RESTRICT,
  model_year   SMALLINT NOT NULL CHECK (model_year BETWEEN 1900 AND 2100),
  list_price   NUMERIC(10,2) NOT NULL CHECK (list_price >= 0)
);

CREATE TABLE orders (
  order_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id   INTEGER REFERENCES customers(customer_id) ON DELETE SET NULL,
  order_status  SMALLINT NOT NULL DEFAULT 1 CHECK (order_status BETWEEN 1 AND 6),
  order_date    DATE NOT NULL DEFAULT CURRENT_DATE,
  required_date DATE,
  shipped_date  DATE,
  store_id      INTEGER NOT NULL REFERENCES stores(store_id) ON DELETE RESTRICT,
  staff_id      INTEGER NOT NULL REFERENCES staffs(staff_id) ON DELETE RESTRICT
);

CREATE TABLE order_items (
  order_id   INTEGER NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
  item_id    INTEGER NOT NULL,
  product_id INTEGER NOT NULL REFERENCES products(product_id) ON DELETE RESTRICT,
  quantity   INTEGER NOT NULL CHECK (quantity > 0),
  list_price NUMERIC(10,2) NOT NULL CHECK (list_price >= 0),
  discount   NUMERIC(4,2)  NOT NULL DEFAULT 0 CHECK (discount >= 0 AND discount <= 1),
  PRIMARY KEY (order_id, item_id)
);

CREATE TABLE stocks (
  store_id   INTEGER NOT NULL REFERENCES stores(store_id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,
  quantity   INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  PRIMARY KEY (store_id, product_id)
);